name: scrape_configs

on:
  pull_request:

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Start the app with Gunicorn (like Railway)
      run: |
        # Run your app in the background
        gunicorn --workers 1 --threads 8 -b 0.0.0.0:8000 app.main.app &
        sleep 3

    - name: Check if /metrics is responding
      run: |
        curl -f http://localhost:8000/metrics || (echo "App failed to start" && exit 1)

    - name: check if /t/test returns a redirect
      run: |
        curl -I http://localhost:8000/t/test || (echo "Tracking route faield" && exit 1)
