services:
  qr-tracker:
    build: .
    image: qr-tracker:dev
    env_file:
      - .env            # contains TARGET_URL=...
    ports:
      - "8000:8000"     # host:container
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - qr-tracker
    restart: unless-stopped

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        # optional: show Prometheus by default in the dropdown
        - GF_DEFAULT_INSTANCE_NAME=QR-Stack
      volumes:
        - grafana-data:/var/lib/grafana
        - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      depends_on:
        - prometheus
      restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
